hello-rails-back-end-PR
mmsesay/hello-rails-back-end pull request #1
Opened 2022-02-15 20:30 UTC by mmsesay

In this PR I implemented the following:

- Create a new Rails API app called 'hello-rails-back-end'.
- Initialize your project with Git.
- Make sure that your project has a Postgres database set up.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from your table with an action and rails route.

2022-02-15 22:10 UTC, rukundoeric requested changes
Hi @mmsesay, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ]  There was no way for me to review your front-end since you did not create a pull request for it. as the project requires, you should have created two pull-requests(one for backend which is this one, and another for frontend). Kindly open a pull request for frontend as well. and remember to include its link in either README or PR Description. preferably in PR Description.
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-15 22:10 UTC, rukundoeric commented on app/controllers/v1/greeting_controller.rb
> +    render json: { greeting: @messages }.to_json
- [ ] <b>REQUIRED:</b> The project requires to create an action controller which return one a random greeting. but as it is obvious, this action will respond with the list of many greetings. Kindly fix it to comply with project requirements.

2022-02-15 22:16 UTC, mmsesay commented on app/controllers/v1/greeting_controller.rb
> +    render json: { greeting: @messages }.to_json
Thanks @rukundoeric. I have fixed it.

2022-02-15 22:32 UTC, elisha2kyakpo1 requested changes
Hi @mmsesay, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a front end pull request, you should create a pull request for the react app.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-02-16 00:00 UTC, andersonlebon approved these changes
## Hi @mmsesay 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-16 00:00 UTC, andersonlebon commented on app/controllers/v1/greeting_controller.rb
> +    @random = @messages[rand(0..(@messages.count - 1))]
## [OPTIONAL]

- [ ] Noce job Implementing the feature of getting a greeting message randomly however I would strongly suggest you implement the scenario when the greeting table is empty because currently is raising an error. check :clap: 
![image](https://user-images.githubusercontent.com/65068771/154169364-e4e990a0-4357-47d0-a594-6464b86dcf96.png)

Youc an use this condition to solve it 
```rb    
@random = @messages[rand(0..(@messages.count ||  0 - 1))] 

or  you can use

 @random = @messages[rand(0..(@messages.count))] 


```

2022-02-16 00:07 UTC, mmsesay commented on app/controllers/v1/greeting_controller.rb
> +    @random = @messages[rand(0..(@messages.count - 1))]
Thanks. I have added it.

2022-02-16 00:07 UTC, merged